TheBirdsOfWar Frank FizzBuzz
JoinTheGang i Dennis Milksteak 1
Rickety i 0 MagnumCondoms 100 1
Dayman BlastMe BlastMe i PayTheTrollToll 3 InTheAss ReadyToPlow 0 InTheAss LiamMcPoyle BlastMe BlastMe i PayTheTrollToll 5 InTheAss ReadyToPlow 0 InTheAss
BangTheWaitress "FizzBuzz"
FighterOfTheNightman BlastMe i PayTheTrollToll 3 InTheAss ReadyToPlow 0
BangTheWaitress "Fizz"
FighterOfTheNightman BlastMe i PayTheTrollToll 5 InTheAss ReadyToPlow 0
BangTheWaitress "Buzz"
ChampionOfTheSun
BangTheWaitress i
MasterOfKarateAndFriendshipForEveryone
Cricket
TheTrashman

FizzBuzz